version: "3.3"

services:
  app:
    build: ./blogs
    container_name: "blogs-backend"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./blogs:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file:
      - ./blogs/.env
    volumes:
      - postgres-db-vol:/var/lib/postgresql/data

volumes:
  postgres-db-vol:

