# Generated by Django 3.2.9 on 2024-09-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAuthToken',
        ),
    ]
