# Generated by Django 3.2.9 on 2024-09-06 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0003_delete_adminauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token identifier', primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50, null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
