# Generated by Django 3.2.9 on 2024-09-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xuser', '0003_adminuser'),
        ('xauth', '0004_adminauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xuser.adminuser'),
        ),
    ]
